### ISSUE TITLE
Docker: Unable to Access UI

### ISSUE THREAD

**Issue by maniche04** [agentproxy-dev/agentproxy#104]
Hi, 

I used the Dockerfile available in repo with a docker compose file below:

```
services:

  agentgateway:

    build: .

    ports:

      - 19000:19000
      
      - 3000:3000
      
    volumes:

      - ./config.json:/root/.config/agentgateway/config.json
```

I am able to access the SSE endpoint at localhost:3000/sse, but I can't access localhost:19000.
