### ISSUE TITLE
Add ability to pass through HTTP headers from gateway to API when using MCP target

### ISSUE THREAD

**Issue by asaintsever** [agentproxy-dev/agentproxy#129]
Currently, the gateway only provides API endpoints exposed via OpenAPI MCP target with the HTTP Authorization header (and only if passthrough authentication is enabled).

As APIs often require additional standard or custom HTTP headers, in particular additional headers specified in the `securitySchemes` section of the OpenAPI file: we need a way to tell the gateway to forward such headers too.

Several options:

- we forward all HTTP headers set on gateway call to the API endpoints
- we define some header names allow-list (exact name, wildcard, regex patterns: eg "x-*" to allow all custom headers) in gateway config/UI at the MCP Server level, and the gateway only forwards the matching headers to the API endpoints

The UI playground must also be updated to allow definition of headers to provide to the API endpoints when clicking the Run Tool button.

**Comment by mkostreba** [comment]
## Current State Analysis

- The gateway currently only forwards the Authorization header via backend authentication policies
- Headers must be manually specified in each MCP tool call under the "header" parameter
- No automatic forwarding of headers from the original gateway request to target APIs

## Recommended Solution

I recommend implementing __Option 2: Configurable Header Allow-List__ which provides:

### Key Benefits:

- __Security__: Only explicitly configured headers are forwarded (default deny approach)
- __Flexibility__: Supports exact names, wildcards, and regex patterns
- __Granular Control__: Per-MCP target configuration
- __Backward Compatibility__: No breaking changes to existing functionality

### Configuration Example:

```yaml
targets:
- name: openapi
  openapi:
    schema:
      file: ./openapi.json
    host: localhost
    port: 8080
    headerForwarding:
      allowList:
        - "X-API-Key"
        - "X-Request-ID"
      patterns:
        - "X-*"
      denyList:
        - "X-Internal-*"
```

## Implementation Plan:

1. __Phase 1__: Basic allow-list configuration and forwarding
2. __Phase 2__: Pattern matching (wildcards and regex)
3. __Phase 3__: UI playground updates
4. __Phase 4__: Advanced features (transformations, auto-detection)

## Security Considerations:

- Default deny approach with no headers forwarded unless explicitly configured
- Built-in protection for sensitive headers (Cookie, Set-Cookie, X-Forwarded-*, Host)
- Pattern validation to prevent ReDoS attacks
- Header size and count limits

## Alternative Approaches Evaluated:

- __Forward All Headers__: Rejected due to security risks and header pollution
- __OpenAPI Security Scheme Auto-Detection__: Considered for future enhancement
- __Header Transformation Rules__: Identified as advanced future feature
- __Per-Tool Configuration__: Rejected due to configuration complexity

**Comment by howardjohn** [comment]
Now that we are a generic reverse proxy it makes more sense to forward all headers IMO. Users can remove the headers already using `filters`

**Comment by mkostreba** [comment]
You are so right. I'm just learning this codebase so I missed that. That being said....
I recommend that we implement a **simplified version** that forwards all headers by default but with **built-in security protections** for sensitive headers, and provide a simple configuration override.

```yaml
targets:
- name: openapi-service
  openapi:
    schema:
      file: ./openapi.json
    host: api.example.com
    port: 443
    # NEW: Simple header forwarding (optional)
    forwardAllHeaders: true  # Default: false for security
    excludeHeaders:          # Optional: additional exclusions
      - "X-Internal-*"
```

**Comment by howardjohn** [comment]
I really do not think it's the responsibility of the openapi backend to decide what headers to use when we already have a generic mechanism to do so with http filters. One of the goals of the project is moving away from the target specific configuration which we did a major shift towards in the 0.6 release

**Comment by abhimoondra** [comment]
Hey @howardjohn,

Is this the case with SSE or MCP targets as well, where the headers are not forwarded?

I have a SSE target and I am sending `Authorization` header in the request but the agent-gateway is not passing the header to the SSE target. 

This is my agent-gateway config:

```yaml
binds:
- listeners:
  - routes:
    - backends:
      - mcp:
          name: local-proxy
          targets:
          - filters: []
            name: local-proxy
            sse:
              host: localhost
              path: /sse
              port: 45450
      hostnames: []
      matches:
      - path:
          pathPrefix: /my-local-proxy/
      name: my-local-proxy
      policies:
        backendAuth:
          passthrough: {}
  port: 3000
```
